spring.application.name=task-management

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/task_management_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

jwt.secret=${JWT_SECRET:mysupersecretkeymysupersecretkey123456}
jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html